import Foundation
import SafariServices
import UIKit
import WebKit

// MARK: - WKNavigationDelegate & WKUIDelegate

extension AdaWebHost: WKNavigationDelegate, WKUIDelegate {
    public func webView(_ webView: WKWebView, didFinish _: WKNavigation!) {
        guard let callbacks = eventCallbacks else { return }
        let url = webView.url?.absoluteString ?? ""
        callbacks["*"]?(["event_name": "ada.webview.loaded", "url": url])
    }

    public func webView(_: WKWebView, didFailProvisionalNavigation _: WKNavigation!, withError error: Error) {
        // Whena  reset method is built - we will need to set this back to false
        hasError = true
        webViewLoadingErrorCallback?(AdaWebHostError.webViewFailedToLoad)
        guard let callbacks = eventCallbacks else { return }
        callbacks["*"]?(["event_name": "ada.webview.loadFailed", "error": error.localizedDescription])
    }

    /// Shared function to handle opening of urls
    public func openUrl(webView: WKWebView, url: URL) {
        let httpSchemes = ["http", "https"]
        let urlScheme = url.scheme
        // Handle opening universal links within the host App
        // This requires the appScheme argument to work
        if urlScheme == appScheme {
            guard let presentingVC = findViewController(from: webView) else { return }
            presentingVC.dismiss(animated: true) {
                let shared = UIApplication.shared
                if shared.canOpenURL(url) {
                    shared.open(url, options: [:], completionHandler: nil)
                }
            }
            // Only open links in in-app WebView if URL uses HTTP(S) scheme, and the openWebLinksInSafari option is
            // false
            // This is where SUP-43 is likely crashing
        } else if openWebLinksInSafari == false, httpSchemes.contains(urlScheme ?? "") {
            let sfVC = SFSafariViewController(url: url)
            guard let presentingVC = findViewController(from: webView) else { return }
            presentingVC.present(sfVC, animated: true, completion: nil)
        } else {
            let shared = UIApplication.shared
            if shared.canOpenURL(url) {
                shared.open(url, options: [:], completionHandler: nil)
            }
        }
    }

    /// Used for weblinks and signon (handling window.open js call)
    public func webView(
        _ webView: WKWebView,
        createWebViewWith _: WKWebViewConfiguration,
        for navigationAction: WKNavigationAction,
        windowFeatures _: WKWindowFeatures,
    ) -> WKWebView? {
        if let url = navigationAction.request.url {
            openUrl(webView: webView, url: url)
        }
        return nil
    }

    /// Used for processing all other navigation
    public func webView(
        _ webView: WKWebView,
        decidePolicyFor navigationAction: WKNavigationAction,
        decisionHandler: @escaping @MainActor @Sendable (WKNavigationActionPolicy) -> Void,
    ) {
        if #available(iOS 14.5, *), navigationAction.shouldPerformDownload {
            decisionHandler(.download)
        } else if let url = navigationAction.request.url,
                  url.absoluteString.range(of: "/transcript/") != nil
        {
            downloadUrl(url: url, fileName: "chat_transcript.txt")
            decisionHandler(.cancel)
        } else if navigationAction.navigationType == WKNavigationType.linkActivated {
            if let url = navigationAction.request.url {
                openUrl(webView: webView, url: url)
            }
            decisionHandler(.cancel)
        } else {
            decisionHandler(.allow)
        }
    }

    /// Bypasses TLS certificate validation for local dev servers.
    ///
    /// Allows WKWebView to load `webview.html` and all sub-resources from
    /// `localhost` (SDK assets) and to make API fetch calls to `localhost`
    /// (local Ada backend proxy), both of which use self-signed certificates
    /// generated by `@vitejs/plugin-basic-ssl` during `npm run dev`.
    /// Legacy `messaging-assets.net` / `messaging-demo.net` aliases remain
    /// allowed for compatibility with older local setups.
    private static let localDevHosts: Set<String> = [
        "localhost",
        "127.0.0.1",
        "messaging-assets.net",
        "messaging-demo.net",
    ]

    public func webView(
        _: WKWebView,
        didReceive challenge: URLAuthenticationChallenge,
        completionHandler: @escaping @MainActor @Sendable (URLSession.AuthChallengeDisposition, URLCredential?) -> Void,
    ) {
        #if DEBUG
            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust,
               Self.localDevHosts.contains(challenge.protectionSpace.host),
               let trust = challenge.protectionSpace.serverTrust,
               case .local = (environment ?? .production)
            {
                completionHandler(.useCredential, URLCredential(trust: trust))
                return
            }
        #endif
        completionHandler(.performDefaultHandling, nil)
    }

    /// Download the file from the given url and store it locally in the app's temp folder and present the activity
    /// viewer.
    private func downloadUrl(url downloadUrl: URL, fileName: String) {
        let localFileURL = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)

        URLSession.shared.dataTask(with: downloadUrl) { data, response, err in
            guard let data, err == nil else {
                debugPrint("Error downloading from url=\(downloadUrl.absoluteString): \(err.debugDescription)")
                return
            }
            if let httpResponse = response as? HTTPURLResponse {
                debugPrint("HTTP Status=\(httpResponse.statusCode)")
            }
            // write the downloaded data to a temporary folder
            do {
                try data.write(to: localFileURL, options: .atomic) // atomic option overwrites it if needed
                DispatchQueue.main.async { [weak self] in
                    guard let self, let webView else { return }
                    // present activity viewer
                    let items = [localFileURL]
                    let ac = UIActivityViewController(activityItems: items, applicationActivities: nil)
                    findViewController(from: webView)?.present(ac, animated: true)
                }
            } catch {
                debugPrint(error)
            }
        }.resume()
    }
}

// MARK: - WKDownloadDelegate

@available(iOS 14.5, *)
extension AdaWebHost: WKDownloadDelegate {
    public func download(
        _: WKDownload,
        decideDestinationUsing _: URLResponse,
        suggestedFilename: String,
        completionHandler: @escaping @MainActor @Sendable (URL?) -> Void,
    ) {
        let localFileURL = FileManager.default.temporaryDirectory.appendingPathComponent(suggestedFilename)

        completionHandler(localFileURL)

        DispatchQueue.main.async { [weak self] in
            guard let self, let webView else { return }
            // present activity viewer
            let items = [localFileURL]
            let ac = UIActivityViewController(activityItems: items, applicationActivities: nil)
            findViewController(from: webView)?.present(ac, animated: true)
        }
    }

    public func webView(_: WKWebView, navigationAction _: WKNavigationAction, didBecome download: WKDownload) {
        download.delegate = self
    }
}
